=== Apollo3zehn/Python/S0_Files/json-schema/site-assessment/1.0.0.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Site assessment calculation",
    "type": "object",
    "definitions": {
        "sector": {
            "type": "object",
            "properties": {
                "min": {
                    "title": "Minimum angle",
                    "description": "The minimum angle of the sector in degrees.",
                    "type": "number"
                },
                "max": {
                    "title": "Maximum angle",
                    "description": "The maximum angle of the sector in degrees.",
                    "type": "number"
                }
            },
            "required": [
                "min",
                "max"
            ]
        },
        "coordinates": {
            "type": "object",
            "properties": {
                "latitude": {
                    "title": "Latitude",
                    "description": "Decimal WGS 84 latitude value of the object coordinates.",
                    "type": "number"
                },
                "longitude": {
                    "title": "Longitude",
                    "description": "Decimal WGS 84 longitude value of the object coordinates.",
                    "type": "number"
                }
            },
            "required": [
                "latitude",
                "longitude"
            ]
        },
        "obstacle-base": {
            "type": "object",
            "properties": {
                "name": {
                    "title": "Name",
                    "description": "Display name of the object.",
                    "type": "string"
                },
                "coordinates": { 
                    "$ref": "#/definitions/coordinates",
                    "title": "Coordinates",
                    "description": "Decimal WGS 84 coordinates of the object."
                }
            },
            "required": [
                "name",
                "coordinates"
            ]
        },
        "WTG": {
            "title": "Wind turbine generator",
            "description": "The wind turbine under test.",
            "allOf": [
                { 
                    "$ref": "#/definitions/obstacle-base" 
                },
                {
                    "properties": {
                        "hub-height": {
                            "title": "Hub height",
                            "description": "Height of the centre of the swept area of the wind turbine rotor above the ground at the tower in meters.",
                            "type": "number"
                        },
                        "rotor-diameter": {
                            "title": "Rotor diameter",
                            "description": "Diameter of the rotor in meters.",
                            "type": "number"
                        }
                    },
                    "required": [
                        "hub-height",
                        "rotor-diameter"
                    ]
                }
            ]
        },
        "WME": {
            "title": "Wind measurement equipment",
            "description": "The wind measurement equipment like met mast, lidar oder sodar.",
            "allOf": [
                {
                    "$ref": "#/definitions/obstacle-base" 
                }
            ]
        },
        "WTG-obstacle": {
            "allOf": [
                { 
                    "$ref": "#/definitions/WTG" 
                },
                {
                    "properties": {
                        "in-operation": {
                            "title": "Operating status",
                            "description": "If false, the WTG will be treated as a simple obstacle.",
                            "type": "boolean",
                            "default": true
                        },
                        "tower-base-diameter": {
                            "title": "Tower diameter",
                            "description": "Diameter of the tower base in meters.",
                            "type": "number"
                        }
                    },
                    "required": [
                        "in-operation",
                        "tower-base-diameter"
                    ]
                }
            ]
        },
        "other-obstacle": {
            "allOf": [
                { 
                    "$ref": "#/definitions/obstacle-base" 
                },
                {
                    "properties": {
                        "height": {
                            "title": "Height",
                            "description": "Height of the obstacle in meters.",
                            "type": "number"
                        },
                        "width-wtg": {
                            "title": "Width (WTG)",
                            "description": "Width of the obstacle in meters as seen from the WTG under test.",
                            "type": "number"
                        },
                        "width-wme": {
                            "title": "Width (WME)",
                            "description": "Width of the obstacle in meters as seen from the WME.",
                            "type": "number"
                        }
                    },
                    "required": [
                        "height",
                        "width-wtg",
                        "width-wme"
                    ]
                }
            ]
        },
        "satellite-map-settings": {
            "title": "Satellite map settings",
            "description": "Settings for the satellite background image.",
            "type": "object",
            "properties": {
                "source": {
                    "title": "Satellite image provider",
                    "description": "Select a source for the satellite image. If 'local file' is selected, the property 'file-path' must be specified.",
                    "enum": ["Google Maps", "Bing Maps", "local file"],
                    "default": "Bing Maps"
                },
                "zoom-level": {
                    "title": "Satellite zoom level",
                    "description": "Choose a zoom level to include all objects of interest.",
                    "type": "integer",
                    "default": 14
                },
                "scale-factor": {
                    "title": "Background image scale factor",
                    "description": "Specify a scale factor for fine grained scaling of the background image.",
                    "type": "number",
                    "default": 1.0
                },
                "offset-x": {
                    "title": "Offset of image in x-direction",
                    "description": "Useful if the WTG under test is not in the center of the image. Unit: meters.",
                    "type": "number"
                },
                "offset-y": {
                    "title": "Offset of image in y-direction",
                    "description": "Useful if the WTG under test is not in the center of the image. Unit: meters.",
                    "type": "number"
                },
                "file-path": {
                    "title": "File path of an external image file.",
                    "description": "Optional. If specified, the option 'zoom-level' is ignored.",
                    "type": "string"
                }
            },
            "required": [
                "source",
                "zoom-level",
                "scale-factor",
                "offset-x",
                "offset-y"
            ]
        },
        "general-settings": {
            "title": "General settings",
            "description": "Miscellaneous settings.",
            "type": "object",
            "properties": {
                "min-sector-width": {
                    "title": "Minimum width of valid sector.",
                    "description": "This settings helps to sort out sectors which are very small.",
                    "type": "number"
                },
                "min-sector-radius": {
                    "title": "Minimum plotting radius of the valid and disturbed sectors.",
                    "description": "This setting affects the axis limits.",
                    "type": "number",
                    "default": 1000.0
                },
                "excluded-sector-set": {
                    "title": "Exluded sectors.",
                    "description": "List of additional sectors to exclude from the final valid sector, e.g pointing in direction of flow disturbing terrain.",
                    "type": "array",
                    "items": { "$ref": "#/definitions/sector" }
                },
                "terrain-height-set": {
                    "title": "Terrain heights for contour plot.",
                    "description": "The height values are used by the terrain contour plot.",
                    "type": "array",
                    "items": { "type": "number" }
                }
            },
            "required": [
                "min-sector-width",
                "min-sector-radius",
                "excluded-sector-set"
            ]
        }
    },
    "properties": {
        "WME": { 
            "$ref": "#/definitions/WME" 
        },
        "WTG": { 
            "$ref": "#/definitions/WTG"
        },
        "WTG-obstacle-set": {
            "title": "List of wind turbine obstacles",
            "description": "Nearby wind turbines (operating or stopped) may disturb the WTG under test or the WME and must be considered as disturbance sources.",
            "type": "array",
            "items": { "$ref": "#/definitions/WTG-obstacle" }
        },
        "other-obstacle-set": {
            "title": "List of other obstacles",
            "description": "Other obstacles like buildings may disturb the WTG under test or the WME and must be considered as disturbance sources.",
            "type": "array",
            "items": { "$ref": "#/definitions/other-obstacle" }
        },
        "satellite-map-settings": {
            "$ref": "#/definitions/satellite-map-settings"
        },
        "general-settings": {
            "$ref": "#/definitions/general-settings"
        }
    },
    "required": [
        "WME",
        "WTG",
        "WTG-obstacle-set",
        "other-obstacle-set",
        "satellite-map-settings",
        "general-settings"
    ]
}

=== Apollo3zehn/Python/S3_Sample/SiteAssessmentSample/data.site-assessment.json
{
    "WME": {
        "name": "Met. mast",
        "coordinates": {
            "latitude": 53.554582,
            "longitude": 8.622380
        }
    },
    "WTG": {
        "name": "AD5-135 (Lehe-3)",
        "hub-height": 130,
        "rotor-diameter": 135,
        "coordinates": {
            "latitude": 53.550781,
            "longitude": 8.622744
        }
    },
    "WTG-obstacle-set": [
        {
            "name": "AD5-116 (Lehe-1)",
            "hub-height": 110,
            "rotor-diameter": 116,
            "tower-base-diameter": 5,
            "in-operation": true,
            "coordinates": {
                "latitude": 53.561207,
                "longitude": 8.622948
            }
        },
        {
            "name": "AD5-116 (Lehe-2)",
            "hub-height": 110,
            "rotor-diameter": 116,
            "tower-base-diameter": 5,
            "in-operation": false,
            "coordinates": {
                "latitude": 53.556630,
                "longitude": 8.624490
            }
        },
        {
            "name": "Senvion 5M (1)",
            "hub-height": 120,
            "rotor-diameter": 126,
            "tower-base-diameter": 5,
            "in-operation": true,
            "coordinates": {
                "latitude": 53.553858,
                "longitude": 8.631728
            }
        },
        {
            "name": "Senvion 5M (2)",
            "hub-height": 120,
            "rotor-diameter": 126,
            "tower-base-diameter": 5,
            "in-operation": true,
            "coordinates": {
                "latitude": 53.547983,
                "longitude": 8.629427
            }
        },
        {
            "name": "Senvion 5M (3)",
            "hub-height": 120,
            "rotor-diameter": 126,
            "tower-base-diameter": 5,
            "in-operation": true,
            "coordinates": {
                "latitude": 53.545727,
                "longitude": 8.622660
            }
        },
        {
            "name": "Fictional small WTG",
            "hub-height": 20,
            "rotor-diameter": 10,
            "tower-base-diameter": 0.4,
            "in-operation": true,
            "coordinates": {
                "latitude": 53.551357,
                "longitude": 8.627901
            }
        }
    ],
    "other-obstacle-set": [
        {
            "name": "BEG",
            "height": 60,
            "width-wtg": 20,
            "width-wme": 4,
            "coordinates": {
                "latitude": 53.547847,
                "longitude": 8.617918
            }
        }
    ],
    "satellite-map-settings": {
        "source": "Google Maps",
        "zoom-level": 14,
        "scale-factor": 1.29,
        "offset-x": 0,
        "offset-y": 0
    },
    "general-settings": {
        "min-sector-width": 20,
        "min-sector-radius": 1000,
        "excluded-sector-set": [
            {
                "min": 280,
                "max": 290
            }
        ],
        "terrain-height-set": [
            0,
            100,
            200
        ]
    }
}
