=== Apollo3zehn/Python/S0_Files/json-schema/site-assessment.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "id": "tbd",
    "title": "Site assessment calculation",
    "type": "object",
    "definitions": {
        "coordinates": {
            "type": "object",
            "properties": {
                "Latitude": {
                    "type": "number"
                },
                "Longitude": {
                    "type": "number"
                }
            },
            "required": [
                "Latitude",
                "Longitude"
            ]
        },
        "obstacle-base": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "coordinates": { "$ref": "#/definitions/coordinates" }
            },
            "required": [
                "name",
                "coordinates"
            ]
        },
        "WTG": {
            "allOf": [
                { 
                    "$ref": "#/definitions/obstacle-base" 
                },
                {
                    "properties": {
                        "hub-height": {
                            "title": "Hub height",
                            "description": "Height of the centre of the swept area of the wind turbine rotor above the ground at the tower in meters.",
                            "type": "number"
                        },
                        "rotor-diameter": {
                            "title": "Rotor diameter",
                            "description": "Diameter of the rotor in meters.",
                            "type": "number"
                        }
                    },
                    "required": [
                        "hub-height",
                        "rotor-diameter"
                    ]
                }
            ]
        },
        "WME": {
            "allOf": [
                {
                    "$ref": "#/definitions/obstacle-base" 
                }
            ]
        },
        "WTG-obstacle": {
            "allOf": [
                { 
                    "$ref": "#/definitions/WTG" 
                },
                {
                    "properties": {
                        "in-operation": {
                            "title": "Operating status",
                            "description": "If false, the WTG will be treated as a simple obstacle.",
                            "type": "boolean",
                            "default": true
                        },
                        "tower-base-diameter": {
                            "title": "Tower diameter",
                            "description": "Diameter of the tower base in meters.",
                            "type": "number"
                        }
                    },
                    "required": [
                        "in-operation",
                        "tower-base-diameter"
                    ]
                }
            ]
        },
        "other-obstacle": {
            "allOf": [
                { 
                    "$ref": "#/definitions/obstacle-base" 
                },
                {
                    "properties": {
                        "height": {
                            "type": "number"
                        },
                        "width": {
                            "type": "number"
                        }
                    },
                    "required": [
                        "height",
                        "width"
                    ]
                }
            ]
        }
    },
    "properties": {
        "WME": { "$ref": "#/definitions/WME" },
        "WTG": { "$ref": "#/definitions/WTG" },
        "WTG-obstacle-set": {
            "type": "array",
            "items": { "$ref": "#/definitions/WTG-obstacle" }
        },
        "other-obstacle-set": {
            "type": "array",
            "title": "",
            "items": { "$ref": "#/definitions/other-obstacle" }
        }
    },
    "required": [
        "WME",
        "WTG",
        "WTG-obstacle-set",
        "other-obstacle-set"
    ]
}

=== Apollo3zehn/Python/S2_Test/TestData/data.site-assessment.json
{
    "WME": {
        "name": "met mast",
        "coordinates": {
            "Latitude": 53.554582,
            "Longitude": 8.622380
        }
    },
    "WTG": {
        "name": "AD5-135 (Lehe-3)",
        "hub-height": 130,
        "rotor-diameter": 135,
        "coordinates": {
            "Latitude": 53.550781,
            "Longitude": 8.622744
        }
    },
    "WTG-obstacle-set": [
        {
            "name": "AD5-116 (Lehe-1)",
            "hub-height": 110,
            "rotor-diameter": 116,
            "tower-base-diameter": 5,
            "in-operation": false,
            "coordinates": {
                "Latitude": 53.561207,
                "Longitude": 8.622948
            }
        },
        {
            "name": "AD5-116 (Lehe-2)",
            "hub-height": 110,
            "rotor-diameter": 116,
            "tower-base-diameter": 5,
            "in-operation": true,
            "coordinates": {
                "Latitude": 53.556630,
                "Longitude": 8.624490
            }
        },
        {
            "name": "Senvion 5M (1)",
            "hub-height": 120,
            "rotor-diameter": 126,
            "tower-base-diameter": 5,
            "in-operation": true,
            "coordinates": {
                "Latitude": 53.553858,
                "Longitude": 8.631728
            }
        },
        {
            "name": "Senvion 5M (2)",
            "hub-height": 120,
            "rotor-diameter": 126,
            "tower-base-diameter": 5,
            "in-operation": true,
            "coordinates": {
                "Latitude": 53.547983,
                "Longitude": 8.629427
            }
        },
        {
            "name": "Senvion 5M (3)",
            "hub-height": 120,
            "rotor-diameter": 126,
            "tower-base-diameter": 5,
            "in-operation": true,
            "coordinates": {
                "Latitude": 53.545727,
                "Longitude": 8.622660
            }
        },
        {
            "name": "Fictional small WTG",
            "hub-height": 20,
            "rotor-diameter": 10,
            "tower-base-diameter": 0.4,
            "in-operation": true,
            "coordinates": {
                "Latitude": 53.551357,
                "Longitude": 8.627901
            }
        }
    ],
    "other-obstacle-set": [
        {
            "name": "BEG",
            "height": 60,
            "width": 20,
            "coordinates": {
                "Latitude": 53.547847,
                "Longitude": 8.617918
            }
        }
    ]
}
